### ISSUE TITLE
A issue about data_management.py

### ISSUE THREAD

**Issue by tron19920125** [Simoncarbo/Ultras-Sound-Nerve-Segmentation---Kaggle#1]
Hi, Simoncarbo Thanks u for sharing this code.
But When I ran your code , an issue pop up saying pandas.index.IndexEngine.get_loc (Type error).I dont know whats going on. I seems that this error coursing by data_management.py val_indexes=ordering.loc[...].
Can you tell me how to fix that?

**Comment by Simoncarbo** [comment]
It's been a long time without using Pandas... I'm not sure I can help.

What data are you using? The same as the competition? 
How does your train_index look like?

**Comment by tron19920125** [comment]
Yep,is the same as  the competition.
I have solved this problem by deleting slice(None) in "ordering.loc[(validation_subjects,slice(None)),'initial_order']. 
But I am stuck on the other error.

Traceback (most recent call last):
  File "train.py", line 117, in <module>
    model,epoch_history = train_segment(train_imgs,train_masks,train_index,train_i,val_i,factor,factor_val)
  File "train.py", line 63, in train_segment
    model = models.segment()
  File "/home/biancheng/Ultras-Sound-Nerve-Segmentation---Kaggle-master/models.py", line 68, in segment
    mode='concat', concat_axis=1)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 1528, in merge
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 1186, in __init__
    node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 1253, in _arguments_validation
    'Layer shapes: %s' % (input_shapes))
Exception: "concat" mode can only merge layers with matching output shapes except for the concat axis. Layer shapes: [(None, 1, 160, 16), (None, 1, 160, 8), (None, 1, 160, 8)]

**Comment by Simoncarbo** [comment]
The program is confusing theano and tensorflow dimension orderings. I guess you are using tensorflow?

You could change 
inputs = layers.Input((1, nb_rows, nb_cols)) with
inputs = layers.Input((nb_rows, nb_cols,1))
in the models.segment() method

There could be other errors due to tensorflow-incompatitbility. The code was only tested for theano.
